type ClientMessageTranslation {
  es: String
  en: String
}

type PredefinedMessages {
  "Predefined message code"
  code: String!
  type: String!
  translation: ClientMessageTranslation
}

type FareSettings{
  valuePerKilometer: Int
  additionalCost: Int,
  minimalTripCost: Int
}

# type Params {
#    ClientPredefinedMessages: [ClientPredefinedMessages]
# }

"Business Contact info"
type Query {
  #  Params: Params @requireAuth
  PredefinedMessages: [PredefinedMessages] @requireAuth

  "get the fare per kilometer on trip"
  FareSettings(lat: Float, lng: Float): FareSettings @requireAuth
}