type ClientMessageTranslation {
  es: String
  en: String
}

type PredefinedMessages {
  "Predefined message code"
  code: String!
  type: String!
  translation: ClientMessageTranslation
}

# type Params {
#    ClientPredefinedMessages: [ClientPredefinedMessages]
# }

"Business Contact info"
type Query {
  #  Params: Params @requireAuth
  PredefinedMessages: [PredefinedMessages] @requireAuth

  "get the fare per kilometer on trip"
  pricePerKilometerOnTrip: Int @requireAuth
}