
# type GoogleMapsParams {
#   googleMapsBrowserKey: String
# }

type ClientMessageTranslation {
  es: String
  en: String
}

type PredefinedMessages {
  "Predefined message code"
  code: String!
  type: String!
  translation: [ClientMessageTranslation]
}

# type Params {
#    GoogleMapsParams: GoogleMapsParams
#    ClientPredefinedMessages: [ClientPredefinedMessages]
# }

"Business Contact info"
type Query {
  #  Params: Params @requireAuth
  #  GoogleMapsParams: GoogleMapsParams @requireAuth  
  PredefinedMessages: PredefinedMessages @requireAuth
}